repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace

-   repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
    -   id: black
        exclude: ^dist/

-   repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
    -   id: flake8
        args: ["-j8", "--ignore=E501"]
#
-   repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
        - id: isort
          args: [ "--multi-line=5", "--line-length=120", "--use-parentheses", "--filter-files" ]
          exclude: "migrations"
          stages: [ commit ]
    name: isort (python)
#
#-   repo: https://github.com/pre-commit/mirrors-mypy
#    rev: v1.4.1
#    hooks:
#    -   id: mypy
#        verbose: true
#        entry: bash -c 'mypy "$@" || true' --
