
# https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: pytest
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Add python path
        run: |
          echo 'PYTHONPATH<<EOF' >> $GITHUB_ENV
          echo $(pwd) >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run Tests
        run: |
          pytest .

      - name: Run Coverage
        run: |
          ./run_coverage.sh
